config/routes.rb
PersonalSite2::Application.routes.draw do
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :user_sessions

  resources :users

  resources :githubs

  resources :resumes

  resources :works

  resources :projects

  resources :articles;
  root 'home#index'

  get 'about' => "home#about"

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, :subname, :body, presence: true
  has_attached_file :picture, :default_url => "/images/:style/missing.png"
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_login, except:[:index, :show]

  def index
    @projects = Project.all.order("created_at DESC")
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url
  end

  private
    def project_params
      params.require(:project).permit(:name, :subname, :body, :github, :site_link, :picture)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_path, notice: 'Login successful')
    else
      flash.now[:alert] = "Login failed"
      render action: "new"
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login
    
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/githubs_helper.rb
module GithubsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
  <div class = "large-10-centered columns">
    <ul>
    <div>
      <% if current_user %>
        <icon class="fi-x"></icon> <%= link_to "Logout", :logout, method: :post %>
      <% end %>
    </div>
    
    <div>
      <p id = "notice"><%= flash[:notice] %> </p>
      <p id = "alert"><%= flash[:alert] %></p>
    </div>
      
    <div class ="panel">
    <div class = "row">
        <div class="large-6 columns">
          <h2><strong>Hi! I'm </strong></h2><h1><strong>John Tan.</strong></h1>
            <p> I graduated from Baruch College, majored in Computer Information Systems and minored in Mathematics. I grew up in the Lower East Side of Manhattan, New York City. I am currently a Java Developer and I have been exposed to a variety of open sources, such as node.js, angularJs, and mongoDB. My interests lie in Web Application development, Mobile developement, and Big Data. I love singing, health and fitness, traveling, hiking, and exploring natural sceneries! 
            </p>
          </div>

            <div class="large-6 columns">
              <div class = "centered header">
            <%= link_to image_tag("johntan.png", class: "rounded-image"), root_path %>
            </div>
            </div>
        </div>
      </div>

      <div class="row">
        <div class="large-4 columns"> 
            <section class="school">
              <h3><i>Education</i></h3>
              <a class="th [radius]" href="http://www.baruch.cuny.edu" target="_new">
            <img alt="Baruch College" src="https://s3.amazonaws.com/JohnTan/Pictures/BaruchCollege.png" width="200px" />
             </a> 
             <p>
             I was an undergraduate student at <a href="http://www.baruch.cuny.edu" target="_new"> Baruch College </a> studying Computer Information Systems and Mathematics. I am very passionate about people, products, and technology.
            </p>
            </section>

            <section class="school">
              <a class="th [radius]" href="http://www.ccny.cuny.edu" target="_new">
            <img alt="CCNY" src="https://s3.amazonaws.com/JohnTan/Pictures/CCNY.png" width="200px" />
          </a>
           <p>
           Before I attended Baruch College in Fall 2011, I went to <a href="http://www.ccny.cuny.edu" target="_new">The City College of New York</a> for a year, coming right out of high school. I mainly took the General Education coursework and during the time of my studies at CCNY, my favorite subject was <a href= "http://www.khanacademy.org/math/calculus" target="_new"> math</a>. 
           </p>
           </section>
        </div>



        <div class="large-4 columns">
            <section class="work">
              <h3><i>Work Experience</i></h3>
              <a class="th [radius]" href="http://www.standardandpoors.com/" target="_new">
            <img alt="StandardandPoors" src="https://s3.amazonaws.com/JohnTan/Pictures/standardandpoors.png" width="250px" />
              </a>
            <p>
            In the summer of 2013, I was a Data Assurance Intern for the Data Strategy & Operations team at <a href = "http://www.standardandpoors.com/" target="_new"> Standard & Poor's Ratings Services </a> in New York City, an American financial services company that is a division of McGraw Hill Financial. They publish financial research and analysis on stocks and bonds. I was working individually and in teams from New York, London, Denver, and Mumbai. The projects I worked on was predominantly in discrepancy metrics analysis on US Public Finance fundamental data, financial reference data, and scorecard metrics on corporate financial data. The tools I used to work on these projects are Toad for Oracle and MS Access, so I have come to rely on SQL heavily.
            </p>
            </section>

            <section class="work">
              <a class="th [radius]" href="http://www.baruch.cuny.edu" target="_new">
            <img alt="College Advancement" src="https://s3.amazonaws.com/JohnTan/Pictures/CollegeAdvancement.png" width="250px" />
              </a>
            <p>During the spring of 2013, I was an Information Technology Assistant at the Office of College Advancement, Baruch College. My main role was IT Support and Management for the entire office infrastructure on hardware, software, and networks. I also have developed and maintained the infrastructure inventory database and time-sheet database using MS Access. As a side project of my own, I built VBA macros that automatically export e-mail attachments of pdf files from MS Outlook to user's desktop. </p>
            </section>

            <section class="work">
            <a class="th [radius]" href="http://www.conedison.com" target="_new">
            <img alt="Con Edison" src="https://s3.amazonaws.com/JohnTan/Pictures/ConEdison.png" width="250px" />
              </a>
            <p> In the summer of 2012, I received my first internship at <a href = "http://www.conedison.com" target="_new"> Con Edison </a> in the Quality Assurance team as an Engineering Aide. Qaulity Assurance was a new team that was formed in the Customer Operations Group. Con Edison is a regulated utility providing electric, gass, and steam services in New York City and Westchester County, New York. I mainly worked and managed the meter information systems that focused on interval meters. I also have roles on customer operations, data collection and reporting, Data analytics, Database and Information System Quality Testing. As a side project, I designed VBA macros and Queries in MS Access to improve the team's operations.</p>
            </section>
        </div>
        
        <div class="large-4 columns">
            <section class="activity">
              <h3><i>Activities</i></h3>
            <a class="th [radius]" href="http://www.hackru.org" target="_new">
            <img alt="HackRU" src="https://s3.amazonaws.com/JohnTan/Pictures/HackRU.jpg" width="250px" />
              </a>
            <p> In April 2014, I attended <a href = "http://www.hackru.org" target="_new">HackRU</a> at Rutgers University - New Brunswick. HackRU is a 24 hour hackathon. I teamed up with my friend and a student from Rutgers - Bryan Li and Micah T. Moore. We created <a href = "projects"> SigniMail </a> that allows the user to see the important emails without ever checking his or her email, and sends directly via SMS (text message) that outlines the sender, subject line, and a breif portion of the body that contains 600 characters based on the specific keyword that the user enters on the web app. SigniMail was built with PHP, bootstrap, and MySQL database.</p>
            </section>


            <section class="activity">
            <a class="th [radius]" href="http://2014s.pennapps.com" target="_new">
            <img alt="PennApps" src="https://s3.amazonaws.com/JohnTan/Pictures/PennApps.jpg" width="250px" />
              </a>
            <p> In February 2014, I attended <a href = "http://2014s.pennapps.com" target="_new">PennApps</a> at University of Pennsylvania. PennApps is a 48 hour hackathon for hackers to come togther to pitch ideas, and create a hack by the end of the hackathon. I teamed up with fellows who I have met at the hackathon - Tony Xie, Josephy Song, and Waqas Latiff. We built <a href = "http://www.githackacoin.com" target="_new"> HackaCoin (HACK)</a>, a crytocurrency based on "prim number" algorithm to reward students from hackathon communities around the world, along with a web application that is the online wallet and it was built in Ruby on Rails.</p>
            </section>


            <section class="activity">
            <a class="th [radius]" href="https://s3.amazonaws.com/JohnTan/Pictures/CodeForGood.png" target="_new">
            <img alt="Code for Good" src="https://s3.amazonaws.com/JohnTan/Pictures/CodeForGood.png" width="250px" />
              </a>
            <p> In October 2013, I competed in a 24 hour hackathon at the J.P. Morgan Code for Good Challenge. The non-profit organization, The Center of New York City Neighborhoods (CNYCN), run in partnership with J.P. Morgan Chase's Technology for Social Good team, presented a challenge to create a web application targeted at homeowners, advocacy and policy makers that looks at the changes in flood maps that may impact on housing markets and affordability. We built a web application, <a href = "http://www.joshuanoll.com:4334/ripple/#!" target="_new"> Ripple (NYC Floods)</a>, that uses the LAMP framework and bootstrap as a front-end design. We also implemented the web application with JavaScript, Google Mapping's API, Trulia API, Fizber API, and raw data from NASA and NYTimes.</p>
            </section>

            <section class="activity">
             <a class="th [radius]" href="https://contest-reg.dfw.ibm.com/contest/usaca.nsf/MTM/walloffame?open" target="_new">
            <img alt="IBM Master the Mainframe 2013" src="https://s3.amazonaws.com/JohnTan/Pictures/IBM_2013.png" width="200px" />
              </a>
            <p> I competed and earned Wall of Fame in the 2013 IBM Master the Mainframe Contest. I managed to complete part 1 and part 2 challenges in 4/82 days that involves extensive programming with familiarity in advanced system navigation, application development tasks in Java, Python, SQL, COBOL, JCL as well as hands-on experience with multiple mainframe operating systems, such as Linux on System Z, z/VM, z/OS, z/TPF across the parallel sysplex. </p>
            </section>

             <section class="activity">
             <a class="th [radius]" href="https://www.ibm.com/developerworks/university/students/us_canada/walloffame.html" target="_new">
            <img alt="IBM Master the Mainframe 2012" src="https://s3.amazonaws.com/JohnTan/Pictures/IBM_2012.png" width="200px" />
              </a>
            <p> I participated and earned Wall of Fame in the 2012 IBM Master the Mainframe Contest. I managed to complete part 1 and part 2 challenges that involves debugging, programming, and navigation of the z/OS mainframe. One of the memorable challenges I faced was modifying a C program with Job Control Language (JCL) to have abundant lucky numbers and mersenne prime numbers printed. I also have customized an Interactive System Productivity Facility (ISPF) user interface, a z/OS management facility, using advanced ISPF editor commands. Another cool thing I discovered was compiling and executing a Java program through an z/OS Unix Shell environment. </p>
            </section>
     </div>
   </div>
   </ul>
 </div>

app/views/layouts/_footer.html.erb
<footer class = "footer">
  <nav>
      <div class = "right">
      <ul class = "breadcrumbs">
        <li class="unavailable"> &copy 2014 John Tan </li>
      </ul>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div data-magellan-expedition="fixed">
  <div class = "centered">
      <h1><a href="/">John Tan</a></h1>
</div>

<div class = "centered">
  <p>
  <a href="/">Home </a>
  <icon class = "fi-italic"><%= link_to " Projects", projects_path %></icon>
  <icon class = "fi-italic"><%= link_to " Résumé", "https://s3.amazonaws.com/JohnTan/JTan_Resume_Website.pdf", target:"_new" %></icon>

  <icon class = "fi-italic"><a href="/" data-dropdown="drop1" data-options="is_hover:true"> Contact</a></icon>
        <ul id="drop1" class="f-dropdown" data-dropdown-content >
          <li><%= link_to "Linkedin", "http://www.linkedin.com/in/johnctan", target:"_new" %></li>
          <li><%= link_to "Github", "https://github.com/jctan", target:"_new" %></li>
          <li><%= mail_to " jctan00@gmail.com" %></li>
        </ul>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />

  <!--Set the viewport width to device width for mobile --> 
  <meta name = "viewport" content = "width=device-width, initial-scale=1.0" /> 

  <title>John Tan</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/header'%>
  <div class = "row">
    <%= yield %>
  </div>
  <%= javascript_include_tag "application" %>
</body>
<footer>
  <%= render 'layouts/footer' %>
</footer>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { multipart: true } do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subname %><br />
    <%= f.text_field :subname %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :github %><br />
    <%= f.text_field :github %>
  </div>
  <div class="field">
    <%= f.label :site_link %><br />
    <%= f.text_field :site_link %>
  </div>
  <div class="field">
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="large-6 small-centered columns">
   <br />
  <h1 class = "left">Editing Project</h1>
  <hr>

  <%= render 'form' %>

  <br />
  <%= link_to 'Show', @project %> |
  <%= link_to 'Back', projects_path %> |
  <%= link_to "Destroy", @project, method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/projects/index.html.erb
<% provide(:title, "Projects") %>
<div class="large-8 small-centered columns">
   <br />
  <h1 class = "left">Projects</h1>
  <hr>
  <% if current_user %>
    <%= link_to "New Project", new_project_path, class: 'button alert tiny radius round' %>
  <% end %>
  <ul>
    <% @projects.each do |project| %>
      <h3>
        <%= project.name %>
      </h3>
      <h5>
        <%= project.subname %>
      </h5>
      <%= image_tag project.picture.url() %>
      <br /><br />
      <p>
        <%= raw project.body %>
      </p>
      <p>
        <% unless project.github.empty? %>
          <%= link_to "Github", project.github, class: 'button tiny radius round' %>
        <% end %>
        <% unless project.site_link.empty? %>
          <%= link_to "Link", project.site_link, class: 'button tiny radius round' %>
        <% end %>
      </p>

      <div class="left">
      <% if current_user %>
          <%= link_to "Edit", edit_project_path(project.id), class: 'button alert tiny radius round' %>
      <% end %>
    </div>
    <hr>
     <% end %>
  </ul> 
</div>

app/views/projects/new.html.erb
<div class="large-6 small-centered columns">
   <br />
  <h1 class = "left">New Project</h1>
  <hr>

  <%= render 'form' %>

  <br />
  <%= link_to 'Back', projects_path, class: 'button alert tiny radius round left' %>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>
<div class="large-6 small-centered columns">
  <p id="notice"><%= notice %></p>

  <h3>
    <%= @project.name %>
  </h3>
  <h5>
    <%= @project.subname %>
  </h5>
  <%= image_tag @project.picture.url %>
  <br /><br />
  <p>
    <%= raw @project.body %>
  </p>
  <p>
    <% unless @project.github.empty? %>
      <%= link_to "Github", @project.github, class: "button tiny radius round" %>
    <% end %>
    <% unless @project.site_link.empty? %>
      <%= link_to "Link", @project.site_link, class: "button tiny radius round" %>
    <% end %>
  </p>

  <% if current_user %>
    <%= link_to 'Edit', edit_project_path(@project), class:"button alert tiny radius round" %>
    <%= link_to "Destroy", @project, method: :delete, data: { confirm: "Are you sure?" }, class: "button alert tiny radius round" %>
  <% end %>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<% provide(:title, "Login") %>
<div class="large-8 small-centered columns">
  <h1>Login</h1>

  <%= render 'form' %>

  <%= link_to 'Back', user_sessions_path %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "users") %>

<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Crypted password</th>
      <th>Salt</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.crypted_password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>  
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "New User") %>
<div class="large-8 small-centered columns">
  <h1>New user</h1>

  <%= render 'form' %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<% provide(:title, "Show User") %>
<div class="large-8 small-centered columns">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Crypted password:</strong>
    <%= @user.crypted_password %>
  </p>

  <p>
    <strong>Salt:</strong>
    <%= @user.salt %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>